export const Permissions = {
  // ─── Identity ───
  USER: {
    CREATE: 'CREATE_USER',
    VIEW: 'VIEW_USER',
    UPDATE: 'UPDATE_USER',
    DELETE: 'DELETE_USER',
  },
  ROLE: {
    CREATE: 'CREATE_ROLE',
    VIEW: 'VIEW_ROLE',
    UPDATE: 'UPDATE_ROLE',
    DELETE: 'DELETE_ROLE',
  },
  PERMISSION: {
    CREATE: 'CREATE_PERMISSION',
    VIEW: 'VIEW_PERMISSION',
    UPDATE: 'UPDATE_PERMISSION',
    DELETE: 'DELETE_PERMISSION',
  },

  // ─── Catalog ───
  SERVICE: {
    CREATE: 'CREATE_SERVICE',
    VIEW: 'VIEW_SERVICE',
    UPDATE: 'UPDATE_SERVICE',
    DELETE: 'DELETE_SERVICE',
  },
  CATEGORY: {
    CREATE: 'CREATE_CATEGORY',
    VIEW: 'VIEW_CATEGORY',
    UPDATE: 'UPDATE_CATEGORY',
    DELETE: 'DELETE_CATEGORY',
  },
  // ─── Booking ───
  APPOINTMENT: {
    CREATE: 'CREATE_APPOINTMENT',
    VIEW: 'VIEW_APPOINTMENT',
    UPDATE: 'UPDATE_APPOINTMENT',
    DELETE: 'DELETE_APPOINTMENT',
  },
  PAYMENT: {
    CREATE: 'CREATE_PAYMENT',
    VIEW: 'VIEW_PAYMENT',
    UPDATE: 'UPDATE_PAYMENT',
    DELETE: 'DELETE_PAYMENT',
  },
  REVIEW: {
    CREATE: 'CREATE_REVIEW',
    VIEW: 'VIEW_REVIEW',
    UPDATE: 'UPDATE_REVIEW',
    DELETE: 'DELETE_REVIEW',
    MANAGE: 'MANAGE_REVIEW',
  },

  // ─── Messaging ───
  CONVERSATION: {
    CREATE: 'CREATE_CONVERSATION',
    VIEW: 'VIEW_CONVERSATION',
    UPDATE: 'UPDATE_CONVERSATION',
    DELETE: 'DELETE_CONVERSATION',
  },
  MESSAGE: {
    CREATE: 'CREATE_MESSAGE',
    VIEW: 'VIEW_MESSAGE',
    UPDATE: 'UPDATE_MESSAGE',
    DELETE: 'DELETE_MESSAGE',
  },

  // ─── Staff ───
  STAFF_SCHEDULE: {
    CREATE: 'CREATE_STAFF_SCHEDULE',
    VIEW: 'VIEW_STAFF_SCHEDULE',
    UPDATE: 'UPDATE_STAFF_SCHEDULE',
    DELETE: 'DELETE_STAFF_SCHEDULE',
  },
  STAFF_DAY_OFF: {
    CREATE: 'CREATE_STAFF_DAY_OFF',
    REQUEST_OWN: 'REQUEST_OWN_DAY_OFF',
    VIEW: 'VIEW_STAFF_DAY_OFF',
    UPDATE: 'UPDATE_STAFF_DAY_OFF',
    DELETE: 'DELETE_STAFF_DAY_OFF',
    REVIEW: 'REVIEW_STAFF_DAY_OFF',
  },
  STAFF_CALL_IN: {
    CREATE: 'CREATE_STAFF_CALL_IN',
    VIEW: 'VIEW_STAFF_CALL_IN',
    RESPOND: 'RESPOND_STAFF_CALL_IN',
    DELETE: 'DELETE_STAFF_CALL_IN',
  },
  WORKING_HOUR: {
    CREATE: 'CREATE_WORKING_HOUR',
    VIEW: 'VIEW_WORKING_HOUR',
    UPDATE: 'UPDATE_WORKING_HOUR',
    DELETE: 'DELETE_WORKING_HOUR',
  },

  // ─── Notifications ───
  NOTIFICATION: {
    CREATE: 'CREATE_NOTIFICATION',
    VIEW: 'VIEW_NOTIFICATION',
    UPDATE: 'UPDATE_NOTIFICATION',
    DELETE: 'DELETE_NOTIFICATION',
  },

  // ─── Staff management ───
  STAFF: {
    INVITE: 'INVITE_STAFF',
    VIEW:   'VIEW_STAFF',
    UPDATE: 'UPDATE_STAFF',
    REMOVE: 'REMOVE_STAFF',
  },

  // ─── Store ───
  STORE: {
    CREATE: 'CREATE_STORE',
    VIEW: 'VIEW_STORE',
    UPDATE: 'UPDATE_STORE',
    DELETE: 'DELETE_STORE',
    APPROVE: 'APPROVE_STORE',
  },

  // ─── System Log ───
  LOG: {
    VIEW: 'VIEW_LOG',
    VIEW_SHOP: 'VIEW_SHOP_LOG',
  },

  // ─── Analytics ───
  REPORT: {
    VIEW: 'VIEW_REPORT',
  },

  // ─── Coupon ───
  COUPON: {
    CREATE: 'CREATE_COUPON',
    VIEW: 'VIEW_COUPON',
    UPDATE: 'UPDATE_COUPON',
    DELETE: 'DELETE_COUPON',
    MANAGE: 'MANAGE_COUPON', // tạo platform-wide coupon (admin only)
  },

  // ─── Promotion ───
  PROMOTION: {
    CREATE: 'CREATE_PROMOTION',
    VIEW: 'VIEW_PROMOTION',
    UPDATE: 'UPDATE_PROMOTION',
    DELETE: 'DELETE_PROMOTION',
  },
} as const;

type PermissionGroup = (typeof Permissions)[keyof typeof Permissions];
export type PermissionCode = PermissionGroup[keyof PermissionGroup];

export const ALL_PERMISSION_CODES = Object.values(Permissions).flatMap((group) =>
  Object.values(group),
) as PermissionCode[];
